name: Update file on PR merge

on:
  pull_request:
    branches:
      - release
    types: closed

jobs:
  update_date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read current version
        id: read_version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Increment version
        id: increment_version
        run: echo "::set-output name=version::$((${{ steps.read_version.outputs.version }} + 1))"

      - name: Update version.txt
        run: echo "${{ steps.increment_version.outputs.version }}" > version.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "gitbot@openrct2.org"
          git config --global user.name "OpenRCT2 git bot"
          git commit -am "Bump version to ${{ steps.increment_version.outputs.version }}"
          git push
